### PR TITLE
Migrate local db from sqlite to postgres + add db snapshots

### PR DESCRIPTION
**Pull request by kidzegeye**
## Overview

Changed the local database so that data is stored using postgres
**Note** need to setup a local postgres db to run the code now

## Changes Made

- Changed local dbms to postgres
- Modified field character limits
- Added db snapshots

## Test Coverage

Checked /cdn/populate endpoint

### CODE REVIEW

**Review by snajima — APPROVED** [review]
thanks for the hard work kidus 🎉

**Review by snajima — CHANGES_REQUESTED** [review]
actually, do you mind quickly typing up the steps to set up the postgres database in the `README`

**Review by snajima — APPROVED** [review]
amazinggg ~ tysm kidus

**Review by markim21 — APPROVED** [review]
lgtm!

**Pull request merged**
